[package]
name = "lokalite-windows-hello-tauri-prototype"
version = "0.1.0"
edition = "2024"
publish = false

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2.11.5", features = ["tray-icon", "image-ico"] }
tauri-plugin-single-instance = "2.4.3"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
  "Foundation",
  "Security_Credentials_UI",
  "Win32_Foundation",
  "Win32_System_WinRT",
] }
windows-future = "0.3.2"
